In [1]:
%matplotlib inline
import sys
print(sys.version)
import numpy as np
print(np.__version__)
import pandas as pd
print(pd.__version__)
import matplotlib.pyplot as plt
from pandas_datareader import data, wb
from datetime import timedelta

3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)]
1.11.0
0.18.0


In [2]:
def fixtemp(value):
    if (value == ' '):
        value = np.nan
    elif float(value) < 20.0:
        value = np.nan
    elif type(value) == str:
        value = float(value)
    return value

def fixhumid(value):
    if float(value) > 100.0:
        value = np.nan
    return value

def fixbar(value):
    if value > 35:
        value = value/10
    return value * 100

def makestring(value):
    return str(value)[0:11]

def changetime(value):
    zonemap = {'EDT': 5, 'CDT': 6, 'MDT': 7, 'PDT': 8, 'MST': 8}
    return timedelta(hours=zonemap[value])
    
def getstation(remarkstring):
    for position in range(len(remarkstring)):
        if remarkstring[position] == "K":
            return remarkstring[position:position+4]

all_cols = ['month', 'day', 'year', 'hour', 'minute', 'timezone', 'dirtytemp', 'dirtyhumidity', 'windspKts', \
                'gustKts', 'winddir', 'qualchkflag', 'sealvlpresIn', 'dirtybar', \
                'preschg', 'weathercond', 'visibilMi', 'remark', 'stationID', 'dewptF']
keep_cols = ['month', 'day', 'year', 'hour', 'minute', 'timezone', 'dirtytemp', 'dirtyhumidity', \
             'dirtybar', 'stationID']

weather = pd.read_csv("MLB_Weather_Data.csv", header=None, names=all_cols, usecols=keep_cols, \
                     dtype={'timezone': str, 'year':int, 'month':int, 'day':int, 'hour':int, 'minute':int})

weather['timestamp'] = pd.to_datetime(weather['year'].apply(makestring) + "-" + \
                        weather['month'].apply(makestring) + "-" + \
                        weather['day'].apply(makestring) + " " + \
                        weather['hour'].apply(makestring) + ":" + \
                        weather['minute'].apply(makestring) + ":00")
weather['gmt'] = weather.timestamp + weather.timezone.apply(changetime)
weather['stationID'] = weather.stationID.apply(getstation)
weather['tempF'] = weather.dirtytemp.apply(fixtemp).interpolate()
weather.tempF = weather.tempF.apply(int)
weather['relhum'] = weather.dirtyhumidity.apply(fixhumid).interpolate()
weather.relhum = weather.relhum.apply(int)
weather['altibarom'] = weather.dirtybar.apply(fixbar).interpolate()
weather.altibarom = weather.altibarom.apply(int)/100
del weather['month']
del weather['day']
del weather['year']
del weather['hour']
del weather['minute']
del weather['timezone']
del weather['timestamp']
del weather['dirtytemp']
del weather['dirtyhumidity']
del weather['dirtybar']
weather.set_index('gmt')

/Users/pyvarjan/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


stationID  tempF  relhum  altibarom
gmt                                                    
2015-10-11 04:51:00      KLGA     57      62      30.07
2015-10-11 03:51:00      KLGA     57      57      30.08
2015-10-11 02:51:00      KLGA     57      55      30.08
2015-10-11 01:51:00      KLGA     59      48      30.07
2015-10-11 00:51:00      KLGA     60      46      30.09
2015-10-10 23:51:00      KLGA     61      36      30.06
2015-10-10 22:51:00      KLGA     63      34      30.06
2015-10-10 21:51:00      KLGA     63      35      30.06
2015-10-10 20:51:00      KLGA     64      34      30.07
2015-10-10 19:51:00      KLGA     63      37      30.09
2015-10-10 18:51:00      KLGA     62      38      30.11
2015-10-10 17:51:00      KLGA     60      40      30.12
2015-10-10 16:51:00      KLGA     59      44      30.13
2015-10-10 15:51:00      KLGA     57      49      30.13
2015-10-10 14:51:00      KLGA     55      51      30.13
2015-10-10 13:51:00      KLGA     53      56      30.13
2015-10-10 12:51:00      KLGA     52      61      30.11
2015-10-10 11:51:00      KLGA     52      59      30.08
2015-10-10 10:51:00      KLGA     53      63      30.05
2015-10-10 09:51:00      KLGA     55      59      30.01
2015-10-10 08:51:00      KLGA     55      60      29.97
2015-10-10 07:51:00      KLGA     57      65      29.95
2015-10-10 06:51:00      KLGA     60      67      29.93
2015-10-10 05:51:00      KLGA     62      65      29.89
2015-10-10 04:51:00      KLGA     64      70      29.87
2015-10-10 03:51:00      KLGA     66      75      29.86
2015-10-10 02:51:00      KLGA     66      79      29.84
2015-10-10 01:51:00      KLGA     66      81      29.82
2015-10-10 00:51:00      KLGA     66      84      29.80
2015-10-09 23:51:00      KLGA     66      84      29.78
...                       ...    ...     ...        ...
2015-03-31 06:58:00      KSLI     58      90      30.01
2015-03-31 05:58:00      KSLI     60      88      30.00
2015-03-31 04:58:00      KSLI     61      82      29.99
2015-03-31 03:58:00      KSLI     63      85      29.96
2015-03-31 02:58:00      KSLI     69      64      29.95
2015-03-31 01:58:00      KSLI     71      65      29.94
2015-03-31 00:58:00      KSLI     74      57      29.94
2015-03-30 22:58:00      KSLI     72      60      29.97
2015-03-30 21:58:00      KSLI     73      60      29.99
2015-03-30 20:58:00      KSLI     74      57      30.01
2015-03-30 19:58:00      KSLI     71      58      30.03
2015-03-30 18:58:00      KSLI     66      72      30.04
2015-03-30 18:50:00      KSLI     66      73      30.04
2015-03-30 17:58:00      KSLI     63      86      30.04
2015-03-30 17:53:00      KSLI     60      88      30.05
2015-03-30 17:03:00      KSLI     60      88      30.04
2015-03-30 16:58:00      KSLI     60      88      30.03
2015-03-30 15:58:00      KSLI     59      91      30.03
2015-03-30 15:13:00      KSLI     59      94      30.02
2015-03-30 14:58:00      KSLI     59      93      30.01
2015-03-30 13:58:00      KSLI     59      96      30.00
2015-03-30 13:48:00      KSLI     59     100      30.00
2015-03-30 13:13:00      KSLI     59     100      29.99
2015-03-30 12:58:00      KSLI     59      98      29.99
2015-03-30 11:58:00      KSLI     56     100      29.99
2015-03-30 11:43:00      KSLI     55     100      29.99
2015-03-30 10:58:00      KSLI     57     100      29.99
2015-03-30 10:38:00      KSLI     55     100      30.00
2015-03-30 09:58:00      KSLI     57     100      30.01
2015-03-30 08:58:00      KSLI     58      97      30.02

[160342 rows x 4 columns]

In [3]:
weather.dtypes

stationID            object
gmt          datetime64[ns]
tempF                 int64
relhum                int64
altibarom           float64
dtype: object

In [4]:
weather.stationID.unique()

array(['KLGA', 'KNYC', 'KBOS', 'KPHL', 'KBWI', 'KDCA', 'KATL', 'KSPG',
       'KMIA', 'KMKC', 'KMSP', 'KMDW', 'KBKL', 'KORD', 'KMKE', 'KDET',
       'KCPS', 'KPIT', 'KLUK', 'KDAL', 'KDEN', 'KCQT', 'KBFI', 'KSAN',
       'KOAK', 'KEFD', 'KPHX', 'KSFO', 'KSLI'], dtype=object)

In [ ]:
stationmap = {'NYY':'KNYC', 'BOS':'KBOS', 'BAL':'KBWI', 'TAM':'KSPG',
             'NYM':'KLGA', 'ATL':'KATL', 'PHI':'KPHL', 'WAS':'KDCA', 'MIA':'KMIA',
             'CWS':'KMDW', 'CLE':'KBKL', 'DET':'KDET', 'KCR':'KMKC', 'MIN':'KMSP',
             'CWC':'KORD', 'CIN':'KLUK', 'MIL':'KMKE', 'PIT':'KPIT', 'STL':'KCPS',
             'HOU':'KEFD', 'ANA':'KSLI', 'OAK':'KOAK', 'SEA':'KBFI', 'TEX':'KDAL',
             'ARI':'KPHX', 'COL':'KDEN', 'LAD':'KCQT', 'SDP':'KSAN', 'SFG':'KSFO'
             }

In [5]:
weather.tempF.unique()

array([ 57,  59,  60,  61,  63,  64,  62,  55,  53,  52,  66,  69,  75,
        78,  73,  70,  68,  71,  72,  54,  51,  50,  48,  77,  81,  80,
        79,  82,  84,  86,  87,  88,  90,  93,  91,  89,  46,  45,  42,
        39,  41,  44,  43,  56,  37,  36,  34,  35,  33,  96,  95,  32,
        30,  76,  97,  28,  27,  26,  38,  31,  29,  40,  98, 100,  99,
       102, 104, 105, 107, 106,  92,  67,  65, 108, 111, 109, 113, 114,
       116,  74,  83,  94, 103, 101,  85,  58,  49,  47])

In [6]:
weather.relhum.unique()

array([ 62,  57,  55,  48,  46,  36,  34,  35,  37,  38,  40,  44,  49,
        51,  56,  61,  59,  63,  60,  65,  67,  70,  75,  79,  81,  84,
        83,  87,  73,  54,  64,  58,  66,  71,  76,  86,  80,  78,  72,
        52,  69,  53,  47,  77,  45,  50,  74,  82,  89,  90,  93,  68,
        88,  85,  94,  91,  43,  42,  39,  31,  32,  29,  33,  41,  30,
        28,  27,  26,  25,  96, 100,  92,  19,  20,  17,  23,  97,  15,
        22,  24,  18,  16,  21,  14,  13,  12,  95,  99,  98,   9,   8,
        10,  11,   7,   6,   5,   4,   3,   2])

In [7]:
weather.altibarom.unique()

array([ 30.07,  30.08,  30.09,  30.06,  30.11,  30.12,  30.13,  30.05,
        30.01,  29.97,  29.95,  29.93,  29.89,  29.87,  29.86,  29.84,
        29.82,  29.8 ,  29.78,  29.77,  29.74,  29.76,  29.92,  29.99,
        30.  ,  30.02,  30.03,  30.1 ,  30.14,  30.15,  30.04,  29.98,
        29.94,  29.96,  30.17,  30.18,  30.2 ,  30.21,  30.22,  30.19,
        30.23,  30.24,  30.25,  30.26,  30.27,  30.28,  30.31,  30.33,
        30.34,  30.35,  30.32,  30.3 ,  30.29,  30.16,  29.85,  29.83,
        29.81,  29.73,  29.71,  29.69,  29.68,  29.67,  29.66,  29.9 ,
        29.91,  30.36,  30.39,  30.4 ,  30.42,  30.44,  30.46,  30.47,
        30.45,  30.48,  30.43,  30.41,  30.38,  30.37,  29.88,  29.72,
        29.7 ,  29.65,  29.64,  29.79,  29.75,  29.63,  29.61,  29.6 ,
        29.58,  29.57,  29.59,  29.62,  29.56,  29.55,  29.53,  29.54,
        30.49,  29.51,  29.48,  29.46,  29.5 ,  29.52,  30.5 ,  30.51,
        29.49,  30.52,  30.53,  29.45,  29.42,  29.41,  29.43,  29.4 ,
      

In [8]:
weather.to_csv('Clean_Weather.csv')